### ISSUE TITLE
[Feat] 메인 페이지

### ISSUE THREAD

**Issue by leehyewon0531** [KUSITMS-27-chilling/Encore-FE#20]
## Description
메인 페이지 구현

## Todo

- [x] 로그인/로그아웃
- [x] 헤더 구현
- [x] 관심센터 소식 구현
- [x] 관심센터 설정 모달 구현 ★
- [x] 미니 프로필 구현 ★
- [x] 프로그램 카드 구현
- [x] 프로그램 카드 누르면 상세로 이동

## Etc
- 폰트 크기 등 수정 가능성 있음
