### ISSUE TITLE
[Feat] 프로그램 상세 페이지

### ISSUE THREAD

**Issue by leehyewon0531** [KUSITMS-27-chilling/Encore-FE#21]
## Description
프로그램 상세보기 클릭 시 나타나는 상세 페이지 구현

## Todo

- [x] 프로그램 상세 카드 구현
- [x] 글쓰기 모달 구현
- [x] 같이듣기 구현
- [x] 수강후기 구현

- [x] 글쓰기 모달 타이틀 css 디테일 수정
- [x] 글쓰기 모달 닫기 버튼 onClick 기능 작동

## Etc
