### ISSUE TITLE
[Feat] 커뮤니티 페이지

### ISSUE THREAD

**Issue by leehyewon0531** [KUSITMS-27-chilling/Encore-FE#22]
## Description
커뮤니티 페이지 구현

## Todo

- [x] 탭바 구현
- [x] 같이 듣기 목록
- [x] 같이 듣기 상세
- [x] 수강 후기 목록
- [x] 수강 후기 상세
- [ ] 자유게시판 목록
- [ ] 자유게시판 상세
- [ ] 각 댓글 + 대댓글

## Etc
- 자유게시판 및 댓글+대댓글은 밋업 때까지 구현 X
- 댓글은 프론트 쪽애서 구현할까 고민
