### ISSUE TITLE
[Feat] 우리 동네 강사 페이지

### ISSUE THREAD

**Issue by leehyewon0531** [KUSITMS-27-chilling/Encore-FE#23]
## Description
우리 동네 강사 페이지 구현

## Todo

- [x] 우동강 카드 구현
- [x] 우동강 목록 구현
- [x] 우동강 상세 페이지 강사정보 구현
- [x] 우동강 상세 페이지 수업정보 구현
- [ ] 우동강 신청폼 구현

**Comment by yeonsuu21** [comment]
우동강 신청폼 구현하는거 시연 대비 버튼만 구현해놓는거 맞을까요?

**Comment by leehyewon0531** [comment]
> 우동강 신청폼 구현하는거 시연 대비 버튼만 구현해놓는거 맞을까요?

DB 완성도에 따라 다를 것 같은데 아마도 api 연결까지는 못하지 않을까 싶습니다...! 되면 진짜 좋지만 안 될 경우 그냥 제출시 성공했다는 팝업 띄우는 정도까지만 구현하고 발표나 보고서에서 한번 짚고 넘어가야 할 것 같긴 해요옹
